"""Stream type classes for tap-cloudpayments."""

from __future__ import annotations

from singer_sdk import typing as th  # JSON Schema typing helpers

from tap_cloudpayments.client import CloudPaymentsStream


class Payments(CloudPaymentsStream):
    """Define custom stream."""

    name = "payments"
    rest_method = "POST"
    path = "/payments/list"
    records_jsonpath = '$.Model[*]'

    primary_keys = ["TransactionId"]
    replication_key = "CreatedDateIso"
    is_sorted = True

    schema = th.PropertiesList(
        th.Property(
            "PublicId",
            th.StringType,
            description="TODO",
        ),
        th.Property(
            "TerminalUrl",
            th.StringType,
            description="TODO",
        ),
        th.Property(
            "TransactionId",
            th.IntegerType,
            description="TODO",
        ),
        th.Property(
            "Amount",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "Currency",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CurrencyCode",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "PaymentAmount",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "PaymentCurrency",
            th.StringType,
            description="TODO",
        ),th.Property(
            "PaymentCurrencyCode",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "InvoiceId",
            th.StringType,
            description="TODO",
        ),th.Property(
            "AccountId",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Email",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Description",
            th.StringType,
            description="TODO",
        ),th.Property(
            "JsonData",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CreatedDate",
            th.StringType,
            description="TODO",
        ),th.Property(
            "PayoutDate",
            th.StringType,
            description="TODO",
        ),th.Property(
            "PayoutDateIso",
            th.DateTimeType,
            description="TODO",
        ),th.Property(
            "PayoutAmount",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "CreatedDateIso",
            th.DateTimeType,
            description="TODO",
        ),th.Property(
            "AuthDate",
            th.StringType,
            description="TODO",
        ),th.Property(
            "AuthDateIso",
            th.DateTimeType,
            description="TODO",
        ),th.Property(
            "ConfirmDate",
            th.StringType,
            description="TODO",
        ),th.Property(
            "ConfirmDateIso",
            th.DateTimeType,
            description="TODO",
        ),th.Property(
            "AuthCode",
            th.StringType,
            description="TODO",
        ),th.Property(
            "TestMode",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "Rrn",
            th.StringType,
            description="TODO",
        ),th.Property(
            "OriginalTransactionId",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "FallBackScenarioDeclinedTransactionId",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "IpAddress",
            th.IPv4Type,
            description="TODO",
        ),th.Property(
            "IpCountry",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IpCity",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IpRegion",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IpDistrict",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IpLatitude",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "IpLongitude",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "CardFirstSix",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardLastFour",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardExpDate",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardType",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardProduct",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardCategory",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IssuerBankCountry",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Issuer",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardTypeCode",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "Status",
            th.StringType,
            description="TODO",
        ),th.Property(
            "StatusCode",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "CultureName",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Reason",
            th.StringType,
            description="TODO",
        ),th.Property(
            "CardHolderMessage",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Type",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "Refunded",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "Name",
            th.StringType,
            description="TODO",
        ),th.Property(
            "Token",
            th.StringType,
            description="TODO",
        ),th.Property(
            "SubscriptionId",
            th.StringType,
            description="TODO",
        ),th.Property(
            "IsLocalOrder",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "HideInvoiceId",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "Gateway",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "GatewayName",
            th.StringType,
            description="TODO",
        ),th.Property(
            "ApplePay",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "AndroidPay",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "MasterPass",
            th.BooleanType,
            description="TODO",
        ),th.Property(
            "TotalFee",
            th.NumberType,
            description="TODO",
        ),th.Property(
            "EscrowAccumulationId",
            th.StringType,
            description="TODO",
        ),th.Property(
            "ReasonCode",
            th.IntegerType,
            description="TODO",
        ),th.Property(
            "WalletType",
            th.StringType,
            description="TODO",
        ),th.Property(
            "InfoShopData",
            th.StringType,
            description="TODO",
        ),
    ).to_dict()
